### ISSUE TITLE
how to install ?

### ISSUE THREAD

**Issue by thenamelessthing** [TechBuckler/PlexGifMaker#4]
Hi, I try to install the docker image but I got this error:

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/a9b4c4f8-70ea-4133-90b3-2a613ac40726)

Here is a screenshot of my docker-compose file:

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/33e121eb-e28e-4d01-a2cb-52242c552b4c)

Any idea?

Thank you for your help!

**Comment by TechBuckler** [comment]
Was adding $$ instead of $ a solution that worked?  Or are you still facing issues?

**Comment by thenamelessthing** [comment]
I will try this evening. Thank for the follow up.

**Comment by thenamelessthing** [comment]
Just tried and doesn't work.

**Comment by TechBuckler** [comment]
Try removing the entire line (FFREPORT).  Does that throw an error as well?

**Comment by thenamelessthing** [comment]
with the additional $

Now I got the same error that if I comment the whole line.

Initially I had taken the content of your docker-compose.yml and integrated it into my own. But to debug, I created a separate file .

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/9b723169-008a-42bb-9e23-e42f7261cb1b)


and now I have this as an error:

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/b505c6d4-0cb4-4725-81e8-3f5c921af924)

**Comment by TechBuckler** [comment]
Try: Add version: "3" to the start of your docker-compose.yml. (https://stackoverflow.com/questions/36724948/docker-compose-unsupported-config-option-for-services-service-web)

**Comment by thenamelessthing** [comment]
a new error, at last some progress!

I asked to chatgpt to help me and here his docker-compose suggestion:

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/34f45a35-ccc5-474c-9d38-1ed38544e1e5)

Now it seem to work, but I got this:

![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/67b9f76b-2c6c-4d31-ba44-0c8d347b2471)


I have enough free space..  


![image](https://github.com/TechBuckler/PlexGifMaker/assets/10235448/a0e22810-924b-4337-8f2e-920506aa4c36)

**Comment by TechBuckler** [comment]
So I would think you would want to keep "context: ." (tells the code that the file's are in the current folder - unless you've moved that around).  And the external: true tells docker that this folder already exists outside of docker. (https://docs.docker.com/compose/compose-file/07-volumes/#external)  Probably less of a big deal to not have that - but could also cause issues I suppose. 
Tried to do a little research on the disk space issue, and these two SO answers seem most relevant: https://stackoverflow.com/questions/53457004/python-oserror-errno-28-no-space-left-on-device https://stackoverflow.com/questions/6998083/python-causing-ioerror-errno-28-no-space-left-on-device-results-32766-h
Trying to think why docker build would be using python, but it looks like docker does use some python for it's internals and cli.  
Looks like trying to clear tmp and cache files might be the solution moving forward.  Let me know if you want to hop on a discord chat or something later today.  Otherwise - happy to keep assisting here as much as I'm able.

**Comment by crispybegs** [comment]
Im also really struggling to get this working.

my compose is:

```
version: '3'
services:
  plexgifmaker:
    build:
      context: /home/pi1/docker  # This should be the root directory containing the 'PlexGifMaker' folder
      dockerfile: PlexGifMaker/Dockerfile
    image: plexgifmaker:latest
    ports:
    -  "9999:9000"
    volumes:
      - /home/pi1/docker/PlexGifMaker/plexgifmaker_keys:/usr/shared/plexgifmaker_keys
      
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+;http://+:9000
      - FFREPORT=file=/app/logs/ffmpeg-$(date +%Y%m%s).log 

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "localhost"
      - "--config"
      - "/home/ngrok/.config/ngrok/ngrok.yml"
    volumes:
      - ./ngrok.yml:/home/ngrok/.config/ngrok/ngrok.yml
    depends_on:
      - plexgifmaker

volumes:
  plexgifmaker_keys:
    name: plexgifmaker_keys
    external: true
```
but all i ever get is

```
**Deployment error**
failed to deploy a stack: plexgifmaker Pulling plexgifmaker Warning unable to prepare context: path "/home/pi1/docker" not found
```
